# Generated by Django 4.2.1 on 2023-05-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_course_enrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
    ]
