# Generated by Django 4.2.1 on 2023-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_remove_customuser_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_date",
        ),
    ]
