# Generated by Django 4.2.1 on 2023-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_remove_course_end_date_remove_course_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
    ]
